/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author Nilton
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        calendario = new javax.swing.JPanel();
        pnlTarefas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listTarefas = new javax.swing.JList();
        btnConcluirTarefa = new javax.swing.JButton();
        btnEditarTarefa = new javax.swing.JButton();
        pnlCalendarioPrincipal = new javax.swing.JPanel();
        pnlExibirTarefas = new javax.swing.JPanel();
        btnExibirTarefas = new javax.swing.JButton();
        configurarCalendario = new javax.swing.JPanel();
        lblDiasUteis = new javax.swing.JLabel();
        segunda = new javax.swing.JCheckBox();
        terça = new javax.swing.JCheckBox();
        quarta = new javax.swing.JCheckBox();
        quinta = new javax.swing.JCheckBox();
        sexta = new javax.swing.JCheckBox();
        sabado = new javax.swing.JCheckBox();
        domingo = new javax.swing.JCheckBox();
        lblHorarios = new javax.swing.JLabel();
        JCB00 = new javax.swing.JCheckBox();
        JCB01 = new javax.swing.JCheckBox();
        JCB02 = new javax.swing.JCheckBox();
        JCB03 = new javax.swing.JCheckBox();
        JCB04 = new javax.swing.JCheckBox();
        JCB05 = new javax.swing.JCheckBox();
        JCB06 = new javax.swing.JCheckBox();
        JCB07 = new javax.swing.JCheckBox();
        JCB08 = new javax.swing.JCheckBox();
        JCB09 = new javax.swing.JCheckBox();
        JCB10 = new javax.swing.JCheckBox();
        JCB11 = new javax.swing.JCheckBox();
        JCB12 = new javax.swing.JCheckBox();
        JCB13 = new javax.swing.JCheckBox();
        JCB14 = new javax.swing.JCheckBox();
        JCB15 = new javax.swing.JCheckBox();
        JCB16 = new javax.swing.JCheckBox();
        JCB17 = new javax.swing.JCheckBox();
        JCB18 = new javax.swing.JCheckBox();
        JCB19 = new javax.swing.JCheckBox();
        JCB20 = new javax.swing.JCheckBox();
        JCB21 = new javax.swing.JCheckBox();
        JCB22 = new javax.swing.JCheckBox();
        JCB23 = new javax.swing.JCheckBox();
        lblSlotDeTempo = new javax.swing.JLabel();
        txtSlotDeTempo = new javax.swing.JTextField();
        lblEscalonamento = new javax.swing.JLabel();
        jRBFifo = new javax.swing.JRadioButton();
        jRBSjf = new javax.swing.JRadioButton();
        lblDataBase = new javax.swing.JLabel();
        txtDataBase = new javax.swing.JTextField();
        lblDadosCalendario = new javax.swing.JLabel();
        btnSalvarConfigurarCalendario = new javax.swing.JButton();
        adiconarTarefa = new javax.swing.JPanel();
        lblDescriçao = new javax.swing.JLabel();
        txtDescriçao = new javax.swing.JTextField();
        lblDataPrevistaInicio = new javax.swing.JLabel();
        txtDataPrevistaInicio = new javax.swing.JTextField();
        lblDataPrevistaFim = new javax.swing.JLabel();
        txtDataPrevistaFim = new javax.swing.JTextField();
        lblDuraçaoTotalPrevista = new javax.swing.JLabel();
        txtDuraçaoTotalPrevista = new javax.swing.JTextField();
        lblDuraçaoMaximaExecuçaoPorDia = new javax.swing.JLabel();
        txtDuraçaoMaximaExecuçaoPorDia = new javax.swing.JTextField();
        btnSalvarAdiconarTarefas = new javax.swing.JButton();
        btnTipo = new javax.swing.JButton();
        lblDadosDaTarefa = new javax.swing.JLabel();
        jCBUrgente = new javax.swing.JCheckBox();
        jCBImportante = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Tarefas - Xoxó&Sid");
        setLocationByPlatform(true);
        setResizable(false);

        listTarefas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listTarefas);

        btnConcluirTarefa.setText("Concluir Tarefa");

        btnEditarTarefa.setText("Editar");

        javax.swing.GroupLayout pnlTarefasLayout = new javax.swing.GroupLayout(pnlTarefas);
        pnlTarefas.setLayout(pnlTarefasLayout);
        pnlTarefasLayout.setHorizontalGroup(
            pnlTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarefasLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(pnlTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarefasLayout.createSequentialGroup()
                        .addComponent(btnEditarTarefa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConcluirTarefa)))
                .addContainerGap())
        );
        pnlTarefasLayout.setVerticalGroup(
            pnlTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarefasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConcluirTarefa)
                    .addComponent(btnEditarTarefa))
                .addContainerGap())
        );

        JXDatePicker dpCalendario = new JXDatePicker();
        pnlCalendarioPrincipal.setLayout(new java.awt.BorderLayout());

        pnlCalendarioPrincipal.add(dpCalendario.getMonthView(), java.awt.BorderLayout.CENTER);

        btnExibirTarefas.setText("Exibir Tarefas");

        javax.swing.GroupLayout pnlExibirTarefasLayout = new javax.swing.GroupLayout(pnlExibirTarefas);
        pnlExibirTarefas.setLayout(pnlExibirTarefasLayout);
        pnlExibirTarefasLayout.setHorizontalGroup(
            pnlExibirTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExibirTarefasLayout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(btnExibirTarefas)
                .addContainerGap())
        );
        pnlExibirTarefasLayout.setVerticalGroup(
            pnlExibirTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExibirTarefasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExibirTarefas)
                .addContainerGap())
        );

        javax.swing.GroupLayout calendarioLayout = new javax.swing.GroupLayout(calendario);
        calendario.setLayout(calendarioLayout);
        calendarioLayout.setHorizontalGroup(
            calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calendarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlExibirTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCalendarioPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        calendarioLayout.setVerticalGroup(
            calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calendarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(calendarioLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pnlCalendarioPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlExibirTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Calendário", calendario);

        lblDiasUteis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDiasUteis.setText("Dias úteis");

        segunda.setText("Segunda");

        terça.setText("Terça");

        quarta.setText("Quarta");

        quinta.setText("Quinta");

        sexta.setText("Sexta");

        sabado.setText("Sábado");

        domingo.setText("Domingo");

        lblHorarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHorarios.setText("Horários");

        JCB00.setText("00:00");

        JCB01.setText("01:00");

        JCB02.setText("02:00");

        JCB03.setText("03:00");

        JCB04.setText("04:00");

        JCB05.setText("05:00");

        JCB06.setText("06:00");

        JCB07.setText("07:00");

        JCB08.setText("08:00");

        JCB09.setText("09:00");

        JCB10.setText("10:00");

        JCB11.setText("11:00");

        JCB12.setText("12:00");

        JCB13.setText("13:00");

        JCB14.setText("14:00");

        JCB15.setText("15:00");

        JCB16.setText("16:00");

        JCB17.setText("17:00");

        JCB18.setText("18:00");

        JCB19.setText("19:00");

        JCB20.setText("20:00");

        JCB21.setText("21:00");

        JCB22.setText("22:00");

        JCB23.setText("23:00");

        lblSlotDeTempo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSlotDeTempo.setText("Slot de tempo (em minutos)");

        lblEscalonamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEscalonamento.setText("Tipo de Escalonamento");

        jRBFifo.setText("FIFO");

        jRBSjf.setText("SJF");

        lblDataBase.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDataBase.setText("Data base:");

        lblDadosCalendario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDadosCalendario.setText("Dados de configuração do calendário");

        btnSalvarConfigurarCalendario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalvarConfigurarCalendario.setText("Salvar Configurações");

        javax.swing.GroupLayout configurarCalendarioLayout = new javax.swing.GroupLayout(configurarCalendario);
        configurarCalendario.setLayout(configurarCalendarioLayout);
        configurarCalendarioLayout.setHorizontalGroup(
            configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configurarCalendarioLayout.createSequentialGroup()
                .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(configurarCalendarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDadosCalendario))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configurarCalendarioLayout.createSequentialGroup()
                        .addGap(0, 467, Short.MAX_VALUE)
                        .addComponent(btnSalvarConfigurarCalendario))
                    .addGroup(configurarCalendarioLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSlotDeTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSlotDeTempo)
                            .addComponent(segunda)
                            .addComponent(terça)
                            .addComponent(quarta)
                            .addComponent(quinta)
                            .addComponent(sexta)
                            .addComponent(sabado)
                            .addComponent(domingo)
                            .addComponent(lblDiasUteis))
                        .addGap(18, 18, 18)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHorarios)
                            .addComponent(JCB10)
                            .addComponent(JCB11)
                            .addComponent(JCB09)
                            .addComponent(JCB08)
                            .addComponent(JCB07)
                            .addComponent(JCB06)
                            .addComponent(JCB00)
                            .addComponent(JCB01)
                            .addComponent(JCB02)
                            .addComponent(JCB03)
                            .addComponent(JCB04)
                            .addComponent(JCB05))
                        .addGap(18, 18, 18)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCB23)
                            .addComponent(JCB19)
                            .addComponent(JCB20)
                            .addComponent(JCB21)
                            .addComponent(JCB22)
                            .addComponent(JCB15)
                            .addComponent(JCB14)
                            .addComponent(JCB13)
                            .addComponent(JCB12)
                            .addComponent(JCB16)
                            .addComponent(JCB17)
                            .addComponent(JCB18))
                        .addGap(54, 54, 54)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBFifo)
                            .addComponent(lblEscalonamento)
                            .addComponent(jRBSjf)
                            .addGroup(configurarCalendarioLayout.createSequentialGroup()
                                .addComponent(lblDataBase)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataBase, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        configurarCalendarioLayout.setVerticalGroup(
            configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configurarCalendarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDadosCalendario)
                .addGap(18, 18, 18)
                .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configurarCalendarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalvarConfigurarCalendario))
                    .addGroup(configurarCalendarioLayout.createSequentialGroup()
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(configurarCalendarioLayout.createSequentialGroup()
                                .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblHorarios)
                                    .addComponent(lblEscalonamento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(configurarCalendarioLayout.createSequentialGroup()
                                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(JCB00)
                                            .addComponent(JCB12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(JCB01)
                                            .addComponent(JCB13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(JCB02)
                                            .addComponent(JCB14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(JCB03)
                                            .addComponent(JCB15))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(JCB04)
                                            .addComponent(JCB16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(JCB05)
                                            .addComponent(JCB17))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(JCB06)
                                            .addComponent(JCB18))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(JCB07)
                                            .addComponent(JCB19))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(JCB08)
                                            .addComponent(JCB20))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(JCB09)
                                            .addComponent(JCB21))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(JCB10)
                                            .addComponent(JCB22))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(JCB11)
                                            .addComponent(JCB23)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configurarCalendarioLayout.createSequentialGroup()
                                        .addComponent(jRBFifo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRBSjf)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblDataBase)
                                            .addComponent(txtDataBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(210, 210, 210))))
                            .addGroup(configurarCalendarioLayout.createSequentialGroup()
                                .addComponent(lblDiasUteis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(segunda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(terça)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quarta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quinta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sexta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sabado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(domingo)
                                .addGap(27, 27, 27)
                                .addComponent(lblSlotDeTempo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSlotDeTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 72, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Configurar Calendário", configurarCalendario);

        lblDescriçao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescriçao.setText("Descrição:");

        lblDataPrevistaInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDataPrevistaInicio.setText("Data prevista para o início da tarefa:");

        lblDataPrevistaFim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDataPrevistaFim.setText("Data prevista para o fim da tarefa:");

        lblDuraçaoTotalPrevista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDuraçaoTotalPrevista.setText("Duraçao total prevista (em minutos):");

        lblDuraçaoMaximaExecuçaoPorDia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDuraçaoMaximaExecuçaoPorDia.setText("Duraçao máxima de execução por dia (em minutos):");

        btnSalvarAdiconarTarefas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalvarAdiconarTarefas.setText("Adicionar Tarefa");

        btnTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTipo.setText("Tipo da Tarefa");

        lblDadosDaTarefa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDadosDaTarefa.setText("Dados da tarefa");

        jCBUrgente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBUrgente.setText("Tarefa Urgente");

        jCBImportante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBImportante.setText("Tarefa Importante");

        javax.swing.GroupLayout adiconarTarefaLayout = new javax.swing.GroupLayout(adiconarTarefa);
        adiconarTarefa.setLayout(adiconarTarefaLayout);
        adiconarTarefaLayout.setHorizontalGroup(
            adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adiconarTarefaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDadosDaTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addGroup(adiconarTarefaLayout.createSequentialGroup()
                        .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDuraçaoMaximaExecuçaoPorDia)
                            .addComponent(txtDescriçao, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescriçao)
                            .addComponent(lblDataPrevistaInicio)
                            .addComponent(txtDataPrevistaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataPrevistaFim)
                            .addComponent(txtDataPrevistaFim, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDuraçaoTotalPrevista)
                            .addComponent(txtDuraçaoTotalPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(adiconarTarefaLayout.createSequentialGroup()
                                .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnTipo)
                                    .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtDuraçaoMaximaExecuçaoPorDia, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCBUrgente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBImportante)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adiconarTarefaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvarAdiconarTarefas)
                .addContainerGap())
        );
        adiconarTarefaLayout.setVerticalGroup(
            adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adiconarTarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDadosDaTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescriçao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescriçao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDataPrevistaInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataPrevistaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDataPrevistaFim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataPrevistaFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDuraçaoTotalPrevista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDuraçaoTotalPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblDuraçaoMaximaExecuçaoPorDia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txtDuraçaoMaximaExecuçaoPorDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBUrgente)
                    .addComponent(jCBImportante))
                .addGap(18, 18, 18)
                .addComponent(btnTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnSalvarAdiconarTarefas)
                .addContainerGap())
        );

        jTabbedPane1.addTab("AdicionarTarefa", adiconarTarefa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox JCB00;
    private javax.swing.JCheckBox JCB01;
    private javax.swing.JCheckBox JCB02;
    private javax.swing.JCheckBox JCB03;
    private javax.swing.JCheckBox JCB04;
    private javax.swing.JCheckBox JCB05;
    private javax.swing.JCheckBox JCB06;
    private javax.swing.JCheckBox JCB07;
    private javax.swing.JCheckBox JCB08;
    private javax.swing.JCheckBox JCB09;
    private javax.swing.JCheckBox JCB10;
    private javax.swing.JCheckBox JCB11;
    private javax.swing.JCheckBox JCB12;
    private javax.swing.JCheckBox JCB13;
    private javax.swing.JCheckBox JCB14;
    private javax.swing.JCheckBox JCB15;
    private javax.swing.JCheckBox JCB16;
    private javax.swing.JCheckBox JCB17;
    private javax.swing.JCheckBox JCB18;
    private javax.swing.JCheckBox JCB19;
    private javax.swing.JCheckBox JCB20;
    private javax.swing.JCheckBox JCB21;
    private javax.swing.JCheckBox JCB22;
    private javax.swing.JCheckBox JCB23;
    private javax.swing.JPanel adiconarTarefa;
    private javax.swing.JButton btnConcluirTarefa;
    private javax.swing.JButton btnEditarTarefa;
    private javax.swing.JButton btnExibirTarefas;
    private javax.swing.JButton btnSalvarAdiconarTarefas;
    private javax.swing.JButton btnSalvarConfigurarCalendario;
    private javax.swing.JButton btnTipo;
    private javax.swing.JPanel calendario;
    private javax.swing.JPanel configurarCalendario;
    private javax.swing.JCheckBox domingo;
    private javax.swing.JCheckBox jCBImportante;
    private javax.swing.JCheckBox jCBUrgente;
    private javax.swing.JRadioButton jRBFifo;
    private javax.swing.JRadioButton jRBSjf;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDadosCalendario;
    private javax.swing.JLabel lblDadosDaTarefa;
    private javax.swing.JLabel lblDataBase;
    private javax.swing.JLabel lblDataPrevistaFim;
    private javax.swing.JLabel lblDataPrevistaInicio;
    private javax.swing.JLabel lblDescriçao;
    private javax.swing.JLabel lblDiasUteis;
    private javax.swing.JLabel lblDuraçaoMaximaExecuçaoPorDia;
    private javax.swing.JLabel lblDuraçaoTotalPrevista;
    private javax.swing.JLabel lblEscalonamento;
    private javax.swing.JLabel lblHorarios;
    private javax.swing.JLabel lblSlotDeTempo;
    private javax.swing.JList listTarefas;
    private javax.swing.JPanel pnlCalendarioPrincipal;
    private javax.swing.JPanel pnlExibirTarefas;
    private javax.swing.JPanel pnlTarefas;
    private javax.swing.JCheckBox quarta;
    private javax.swing.JCheckBox quinta;
    private javax.swing.JCheckBox sabado;
    private javax.swing.JCheckBox segunda;
    private javax.swing.JCheckBox sexta;
    private javax.swing.JCheckBox terça;
    private javax.swing.JTextField txtDataBase;
    private javax.swing.JTextField txtDataPrevistaFim;
    private javax.swing.JTextField txtDataPrevistaInicio;
    private javax.swing.JTextField txtDescriçao;
    private javax.swing.JTextField txtDuraçaoMaximaExecuçaoPorDia;
    private javax.swing.JTextField txtDuraçaoTotalPrevista;
    private javax.swing.JTextField txtSlotDeTempo;
    // End of variables declaration//GEN-END:variables
}
