/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AdicionarTarefaController;
import controller.ConfiguracaoCalendarioController;
import controller.TelaPrincipalController;
import dao.SubtipoTarefaDAO;
import dao.TipoTarefaDAO;
import java.awt.BorderLayout;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import model.Calendario;
import model.SubtipoTarefa;
import model.TipoTarefa;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author Nilton
 */
public class TelaPrincipal extends javax.swing.JFrame {

    
    TelaPrincipalController telaPrincipalController;
    AdicionarTarefaController adicionarTarefaController;
    ConfiguracaoCalendarioController configuracaoCalendarioController;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        telaPrincipalController = new TelaPrincipalController(this);
        adicionarTarefaController = new AdicionarTarefaController();
        configuracaoCalendarioController = new ConfiguracaoCalendarioController(this);
        initComponents();
        telaPrincipalController.inicializarCalendario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        calendario = new javax.swing.JPanel();
        pnlTarefas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listTarefas = new javax.swing.JList();
        btnConcluirTarefa = new javax.swing.JButton();
        btnEditarTarefa = new javax.swing.JButton();
        pnlCalendarioPrincipal = new javax.swing.JPanel();
        pnlExibirTarefas = new javax.swing.JPanel();
        btnExibirTarefas = new javax.swing.JButton();
        configurarCalendario = new javax.swing.JPanel();
        lblHorarios = new javax.swing.JLabel();
        JCB00 = new javax.swing.JCheckBox();
        JCB01 = new javax.swing.JCheckBox();
        JCB02 = new javax.swing.JCheckBox();
        JCB03 = new javax.swing.JCheckBox();
        JCB04 = new javax.swing.JCheckBox();
        JCB05 = new javax.swing.JCheckBox();
        JCB06 = new javax.swing.JCheckBox();
        JCB07 = new javax.swing.JCheckBox();
        JCB08 = new javax.swing.JCheckBox();
        JCB09 = new javax.swing.JCheckBox();
        JCB10 = new javax.swing.JCheckBox();
        JCB11 = new javax.swing.JCheckBox();
        JCB12 = new javax.swing.JCheckBox();
        JCB13 = new javax.swing.JCheckBox();
        JCB14 = new javax.swing.JCheckBox();
        JCB15 = new javax.swing.JCheckBox();
        JCB16 = new javax.swing.JCheckBox();
        JCB17 = new javax.swing.JCheckBox();
        JCB18 = new javax.swing.JCheckBox();
        JCB19 = new javax.swing.JCheckBox();
        JCB20 = new javax.swing.JCheckBox();
        JCB21 = new javax.swing.JCheckBox();
        JCB22 = new javax.swing.JCheckBox();
        JCB23 = new javax.swing.JCheckBox();
        lblSlotDeTempo = new javax.swing.JLabel();
        txtSlotDeTempo = new javax.swing.JTextField();
        lblDadosCalendario = new javax.swing.JLabel();
        btnSalvarConfigurarCalendario = new javax.swing.JButton();
        adiconarTarefa = new javax.swing.JPanel();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lblDataPrevistaInicio = new javax.swing.JLabel();
        lblDataPrevistaFim = new javax.swing.JLabel();
        lblDuracaoTotalPrevista = new javax.swing.JLabel();
        txtDuracaoTotalPrevista = new javax.swing.JTextField();
        lblDuracaoMaximaExecucaoPorDia = new javax.swing.JLabel();
        txtDuracaoMaximaExecucaoPorDia = new javax.swing.JTextField();
        btnSalvarAdiconarTarefas = new javax.swing.JButton();
        lblDadosDaTarefa = new javax.swing.JLabel();
        jCBUrgente = new javax.swing.JCheckBox();
        jCBImportante = new javax.swing.JCheckBox();
        ftxfDataPrevistaInicio = new javax.swing.JFormattedTextField();
        ftxfDataPrevistaFim = new javax.swing.JFormattedTextField();
        cbTiposTarefa = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnAdicionarTipo = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        mbMenu = new javax.swing.JMenuBar();
        mOpcoes = new javax.swing.JMenu();
        miTarefasConcluidas = new javax.swing.JMenuItem();
        miTipoEscalonamento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Tarefas - Xoxó&Sid");
        setLocationByPlatform(true);
        setResizable(false);

        listTarefasModel = new DefaultListModel();
        listTarefas.setModel(listTarefasModel);
        jScrollPane2.setViewportView(listTarefas);

        btnConcluirTarefa.setText("Concluir Tarefa");
        btnConcluirTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirTarefaActionPerformed(evt);
            }
        });

        btnEditarTarefa.setText("Editar");
        btnEditarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTarefaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTarefasLayout = new javax.swing.GroupLayout(pnlTarefas);
        pnlTarefas.setLayout(pnlTarefasLayout);
        pnlTarefasLayout.setHorizontalGroup(
            pnlTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarefasLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(pnlTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarefasLayout.createSequentialGroup()
                        .addComponent(btnEditarTarefa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConcluirTarefa)))
                .addContainerGap())
        );
        pnlTarefasLayout.setVerticalGroup(
            pnlTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarefasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConcluirTarefa)
                    .addComponent(btnEditarTarefa))
                .addContainerGap())
        );

        dpCalendario = new JXDatePicker();
        pnlCalendarioPrincipal.setLayout(new java.awt.BorderLayout());

        pnlCalendarioPrincipal.add(dpCalendario.getMonthView(), java.awt.BorderLayout.CENTER);

        btnExibirTarefas.setText("Exibir Tarefas");
        btnExibirTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirTarefasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlExibirTarefasLayout = new javax.swing.GroupLayout(pnlExibirTarefas);
        pnlExibirTarefas.setLayout(pnlExibirTarefasLayout);
        pnlExibirTarefasLayout.setHorizontalGroup(
            pnlExibirTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExibirTarefasLayout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addComponent(btnExibirTarefas)
                .addContainerGap())
        );
        pnlExibirTarefasLayout.setVerticalGroup(
            pnlExibirTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExibirTarefasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExibirTarefas)
                .addContainerGap())
        );

        javax.swing.GroupLayout calendarioLayout = new javax.swing.GroupLayout(calendario);
        calendario.setLayout(calendarioLayout);
        calendarioLayout.setHorizontalGroup(
            calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calendarioLayout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlExibirTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCalendarioPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        calendarioLayout.setVerticalGroup(
            calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calendarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(calendarioLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pnlCalendarioPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlExibirTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Calendário", calendario);

        lblHorarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHorarios.setText("Horários");

        JCB00.setText("00:00");

        JCB01.setText("01:00");

        JCB02.setText("02:00");

        JCB03.setText("03:00");

        JCB04.setText("04:00");

        JCB05.setText("05:00");

        JCB06.setText("06:00");

        JCB07.setText("07:00");

        JCB08.setText("08:00");

        JCB09.setText("09:00");

        JCB10.setText("10:00");

        JCB11.setText("11:00");

        JCB12.setText("12:00");

        JCB13.setText("13:00");

        JCB14.setText("14:00");

        JCB15.setText("15:00");

        JCB16.setText("16:00");

        JCB17.setText("17:00");

        JCB18.setText("18:00");

        JCB19.setText("19:00");

        JCB20.setText("20:00");

        JCB21.setText("21:00");

        JCB22.setText("22:00");

        JCB23.setText("23:00");

        lblSlotDeTempo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSlotDeTempo.setText("Slot de tempo (em minutos)");

        lblDadosCalendario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDadosCalendario.setText("Dados de configuração do calendário");

        btnSalvarConfigurarCalendario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalvarConfigurarCalendario.setText("Salvar Configurações");
        btnSalvarConfigurarCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarConfigurarCalendarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout configurarCalendarioLayout = new javax.swing.GroupLayout(configurarCalendario);
        configurarCalendario.setLayout(configurarCalendarioLayout);
        configurarCalendarioLayout.setHorizontalGroup(
            configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configurarCalendarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDadosCalendario)
                    .addGroup(configurarCalendarioLayout.createSequentialGroup()
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSlotDeTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSlotDeTempo))
                        .addGap(31, 31, 31)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHorarios)
                            .addComponent(JCB10)
                            .addComponent(JCB11)
                            .addComponent(JCB09)
                            .addComponent(JCB08)
                            .addComponent(JCB07)
                            .addComponent(JCB06)
                            .addComponent(JCB00)
                            .addComponent(JCB01)
                            .addComponent(JCB02)
                            .addComponent(JCB03)
                            .addComponent(JCB04)
                            .addComponent(JCB05))
                        .addGap(18, 18, 18)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCB23)
                            .addComponent(JCB19)
                            .addComponent(JCB20)
                            .addComponent(JCB21)
                            .addComponent(JCB22)
                            .addComponent(JCB15)
                            .addComponent(JCB14)
                            .addComponent(JCB13)
                            .addComponent(JCB12)
                            .addComponent(JCB16)
                            .addComponent(JCB17)
                            .addComponent(JCB18))))
                .addGap(297, 297, 297))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configurarCalendarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalvarConfigurarCalendario)
                .addContainerGap())
        );
        configurarCalendarioLayout.setVerticalGroup(
            configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configurarCalendarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDadosCalendario)
                .addGap(18, 18, 18)
                .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(configurarCalendarioLayout.createSequentialGroup()
                        .addComponent(lblSlotDeTempo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSlotDeTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(configurarCalendarioLayout.createSequentialGroup()
                        .addComponent(lblHorarios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JCB00)
                            .addComponent(JCB12))))
                .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(configurarCalendarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JCB01)
                            .addComponent(JCB13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JCB02)
                            .addComponent(JCB14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JCB03)
                            .addComponent(JCB15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JCB04)
                            .addComponent(JCB16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JCB05)
                            .addComponent(JCB17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JCB06)
                            .addComponent(JCB18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JCB07)
                            .addComponent(JCB19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JCB08)
                            .addComponent(JCB20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JCB09)
                            .addComponent(JCB21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JCB10)
                            .addComponent(JCB22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JCB11)
                            .addComponent(JCB23))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configurarCalendarioLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(btnSalvarConfigurarCalendario)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Configurar Calendário", configurarCalendario);

        lblDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescricao.setText("Descrição:");

        lblDataPrevistaInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDataPrevistaInicio.setText("Data prevista para o início da tarefa:");

        lblDataPrevistaFim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDataPrevistaFim.setText("Data prevista para o fim da tarefa:");

        lblDuracaoTotalPrevista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDuracaoTotalPrevista.setText("Duraçao total prevista (em minutos):");

        lblDuracaoMaximaExecucaoPorDia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDuracaoMaximaExecucaoPorDia.setText("Duraçao máxima de execução por dia (em minutos):");

        btnSalvarAdiconarTarefas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalvarAdiconarTarefas.setText("Adicionar Tarefa");
        btnSalvarAdiconarTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAdiconarTarefasActionPerformed(evt);
            }
        });

        lblDadosDaTarefa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDadosDaTarefa.setText("Dados da tarefa");

        jCBUrgente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBUrgente.setText("Tarefa Urgente");

        jCBImportante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBImportante.setText("Tarefa Importante");

        try {
            ftxfDataPrevistaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftxfDataPrevistaFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cbTiposTarefa.setModel(new comboBoxTipoTarefaModel());
        cbTiposTarefa.removeAllItems();
        ArrayList<TipoTarefa> tipos;
        tipos = TipoTarefaDAO.getAll();
        int cont = 0;
        for(TipoTarefa t: tipos) {
            cbTiposTarefa.insertItemAt(t.getNome(),cont);
            t.setSubtipos(SubtipoTarefaDAO.getAllIdTipo(t.getIdTipoTarefa()));
            cont++;
            for(SubtipoTarefa s: t.getSubtipos()) {
                cbTiposTarefa.insertItemAt("    "+s.getNome(),cont);
                cont++;
            }
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tipo da Tarefa");

        btnAdicionarTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdicionarTipo.setText("Adicionar Novo Tipo");
        btnAdicionarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarTipoActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adiconarTarefaLayout = new javax.swing.GroupLayout(adiconarTarefa);
        adiconarTarefa.setLayout(adiconarTarefaLayout);
        adiconarTarefaLayout.setHorizontalGroup(
            adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adiconarTarefaLayout.createSequentialGroup()
                .addContainerGap(519, Short.MAX_VALUE)
                .addComponent(btnSalvarAdiconarTarefas)
                .addContainerGap())
            .addGroup(adiconarTarefaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adiconarTarefaLayout.createSequentialGroup()
                        .addComponent(ftxfDataPrevistaFim, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(adiconarTarefaLayout.createSequentialGroup()
                            .addComponent(ftxfDataPrevistaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDadosDaTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                            .addGroup(adiconarTarefaLayout.createSequentialGroup()
                                .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDuracaoMaximaExecucaoPorDia)
                                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDescricao)
                                    .addComponent(lblDataPrevistaInicio)
                                    .addComponent(lblDataPrevistaFim)
                                    .addComponent(lblDuracaoTotalPrevista)
                                    .addComponent(txtDuracaoTotalPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(adiconarTarefaLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(adiconarTarefaLayout.createSequentialGroup()
                                                .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtDuracaoMaximaExecucaoPorDia, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jCBUrgente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jCBImportante))
                                            .addGroup(adiconarTarefaLayout.createSequentialGroup()
                                                .addComponent(cbTiposTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnAdicionarTipo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnAtualizar))
                                            .addComponent(jLabel1))))
                                .addGap(0, 277, Short.MAX_VALUE))))))
        );
        adiconarTarefaLayout.setVerticalGroup(
            adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adiconarTarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDadosDaTarefa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDataPrevistaInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxfDataPrevistaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDataPrevistaFim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxfDataPrevistaFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDuracaoTotalPrevista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDuracaoTotalPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblDuracaoMaximaExecucaoPorDia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txtDuracaoMaximaExecucaoPorDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBUrgente)
                    .addComponent(jCBImportante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTiposTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarTipo)
                    .addComponent(btnAtualizar))
                .addGap(22, 22, 22)
                .addComponent(btnSalvarAdiconarTarefas)
                .addContainerGap())
        );

        jTabbedPane1.addTab("AdicionarTarefa", adiconarTarefa);

        mOpcoes.setText("Opções");

        miTarefasConcluidas.setText("Exibir Tarefas Concluídas");
        miTarefasConcluidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTarefasConcluidasActionPerformed(evt);
            }
        });
        mOpcoes.add(miTarefasConcluidas);

        miTipoEscalonamento.setText("Escolher Tipo de Escalonamento");
        miTipoEscalonamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTipoEscalonamentoActionPerformed(evt);
            }
        });
        mOpcoes.add(miTipoEscalonamento);

        mbMenu.add(mOpcoes);

        setJMenuBar(mbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExibirTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirTarefasActionPerformed
        telaPrincipalController.exibirTarefas();
    }//GEN-LAST:event_btnExibirTarefasActionPerformed

    private void btnEditarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTarefaActionPerformed
        telaPrincipalController.editarTarefa();
    }//GEN-LAST:event_btnEditarTarefaActionPerformed

    private void btnSalvarAdiconarTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAdiconarTarefasActionPerformed
        adicionarTarefaController.adicionarTarefa(this);
    }//GEN-LAST:event_btnSalvarAdiconarTarefasActionPerformed

    private void btnAdicionarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarTipoActionPerformed
        AdicionarNovoTipo telaAdicionarNovoTipo = new AdicionarNovoTipo();
        telaAdicionarNovoTipo.setVisible(true);
    }//GEN-LAST:event_btnAdicionarTipoActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        cbTiposTarefa.removeAllItems();
        ArrayList<TipoTarefa> tipos;
        tipos = TipoTarefaDAO.getAll();
        int cont = 0;
        for(TipoTarefa t: tipos) {
            cbTiposTarefa.insertItemAt(t.getNome(),cont);
            t.setSubtipos(SubtipoTarefaDAO.getAllIdTipo(t.getIdTipoTarefa()));
            cont++;
            for(SubtipoTarefa s: t.getSubtipos()) {
                cbTiposTarefa.insertItemAt("    "+s.getNome(),cont);
                cont++;
            }
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void miTipoEscalonamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTipoEscalonamentoActionPerformed
        TelaTipoEscalonamento telaTipoEscalonamento = new TelaTipoEscalonamento();
        telaTipoEscalonamento.setVisible(true);
    }//GEN-LAST:event_miTipoEscalonamentoActionPerformed

    private void btnConcluirTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirTarefaActionPerformed
        telaPrincipalController.concluirTarefa();
    }//GEN-LAST:event_btnConcluirTarefaActionPerformed

    private void btnSalvarConfigurarCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarConfigurarCalendarioActionPerformed
        //configuracaoCalendarioController.salvarConfiguracoes();
    }//GEN-LAST:event_btnSalvarConfigurarCalendarioActionPerformed

    private void miTarefasConcluidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTarefasConcluidasActionPerformed
        TelaTarefasConcluidas telaTarefasConcluidas = new TelaTarefasConcluidas();
        telaTarefasConcluidas.setVisible(true);
    }//GEN-LAST:event_miTarefasConcluidasActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    
    private DefaultListModel listTarefasModel;
    private JXDatePicker dpCalendario;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox JCB00;
    private javax.swing.JCheckBox JCB01;
    private javax.swing.JCheckBox JCB02;
    private javax.swing.JCheckBox JCB03;
    private javax.swing.JCheckBox JCB04;
    private javax.swing.JCheckBox JCB05;
    private javax.swing.JCheckBox JCB06;
    private javax.swing.JCheckBox JCB07;
    private javax.swing.JCheckBox JCB08;
    private javax.swing.JCheckBox JCB09;
    private javax.swing.JCheckBox JCB10;
    private javax.swing.JCheckBox JCB11;
    private javax.swing.JCheckBox JCB12;
    private javax.swing.JCheckBox JCB13;
    private javax.swing.JCheckBox JCB14;
    private javax.swing.JCheckBox JCB15;
    private javax.swing.JCheckBox JCB16;
    private javax.swing.JCheckBox JCB17;
    private javax.swing.JCheckBox JCB18;
    private javax.swing.JCheckBox JCB19;
    private javax.swing.JCheckBox JCB20;
    private javax.swing.JCheckBox JCB21;
    private javax.swing.JCheckBox JCB22;
    private javax.swing.JCheckBox JCB23;
    private javax.swing.JPanel adiconarTarefa;
    private javax.swing.JButton btnAdicionarTipo;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnConcluirTarefa;
    private javax.swing.JButton btnEditarTarefa;
    private javax.swing.JButton btnExibirTarefas;
    private javax.swing.JButton btnSalvarAdiconarTarefas;
    private javax.swing.JButton btnSalvarConfigurarCalendario;
    private javax.swing.JPanel calendario;
    private javax.swing.JComboBox cbTiposTarefa;
    private javax.swing.JPanel configurarCalendario;
    private javax.swing.JFormattedTextField ftxfDataPrevistaFim;
    private javax.swing.JFormattedTextField ftxfDataPrevistaInicio;
    private javax.swing.JCheckBox jCBImportante;
    private javax.swing.JCheckBox jCBUrgente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDadosCalendario;
    private javax.swing.JLabel lblDadosDaTarefa;
    private javax.swing.JLabel lblDataPrevistaFim;
    private javax.swing.JLabel lblDataPrevistaInicio;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDuracaoMaximaExecucaoPorDia;
    private javax.swing.JLabel lblDuracaoTotalPrevista;
    private javax.swing.JLabel lblHorarios;
    private javax.swing.JLabel lblSlotDeTempo;
    private javax.swing.JList listTarefas;
    private javax.swing.JMenu mOpcoes;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JMenuItem miTarefasConcluidas;
    private javax.swing.JMenuItem miTipoEscalonamento;
    private javax.swing.JPanel pnlCalendarioPrincipal;
    private javax.swing.JPanel pnlExibirTarefas;
    private javax.swing.JPanel pnlTarefas;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtDuracaoMaximaExecucaoPorDia;
    private javax.swing.JTextField txtDuracaoTotalPrevista;
    private javax.swing.JTextField txtSlotDeTempo;
    // End of variables declaration//GEN-END:variables

    public JCheckBox getJCB00() {
        return JCB00;
    }

    public JCheckBox getJCB01() {
        return JCB01;
    }

    public JCheckBox getJCB02() {
        return JCB02;
    }

    public JCheckBox getJCB03() {
        return JCB03;
    }

    public JCheckBox getJCB04() {
        return JCB04;
    }

    public JCheckBox getJCB05() {
        return JCB05;
    }

    public JCheckBox getJCB06() {
        return JCB06;
    }

    public JCheckBox getJCB07() {
        return JCB07;
    }

    public JCheckBox getJCB08() {
        return JCB08;
    }

    public JCheckBox getJCB09() {
        return JCB09;
    }

    public JCheckBox getJCB10() {
        return JCB10;
    }

    public JCheckBox getJCB11() {
        return JCB11;
    }

    public JCheckBox getJCB12() {
        return JCB12;
    }

    public JCheckBox getJCB13() {
        return JCB13;
    }

    public JCheckBox getJCB14() {
        return JCB14;
    }

    public JCheckBox getJCB15() {
        return JCB15;
    }

    public JCheckBox getJCB16() {
        return JCB16;
    }

    public JCheckBox getJCB17() {
        return JCB17;
    }

    public JCheckBox getJCB18() {
        return JCB18;
    }

    public JCheckBox getJCB19() {
        return JCB19;
    }

    public JCheckBox getJCB20() {
        return JCB20;
    }

    public JCheckBox getJCB21() {
        return JCB21;
    }

    public JCheckBox getJCB22() {
        return JCB22;
    }

    public JCheckBox getJCB23() {
        return JCB23;
    }

    public JPanel getAdiconarTarefa() {
        return adiconarTarefa;
    }

    public JButton getBtnConcluirTarefa() {
        return btnConcluirTarefa;
    }

    public JButton getBtnEditarTarefa() {
        return btnEditarTarefa;
    }

    public JButton getBtnExibirTarefas() {
        return btnExibirTarefas;
    }

    public JButton getBtnSalvarAdiconarTarefas() {
        return btnSalvarAdiconarTarefas;
    }

    public JButton getBtnSalvarConfigurarCalendario() {
        return btnSalvarConfigurarCalendario;
    }

    public JPanel getCalendario() {
        return calendario;
    }

    public JPanel getConfigurarCalendario() {
        return configurarCalendario;
    }

    public JXDatePicker getDpCalendario() {
        return dpCalendario;
    }

    public JCheckBox getjCBImportante() {
        return jCBImportante;
    }

    public JCheckBox getjCBUrgente() {
        return jCBUrgente;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public JLabel getLblDadosCalendario() {
        return lblDadosCalendario;
    }

    public JLabel getLblDadosDaTarefa() {
        return lblDadosDaTarefa;
    }

    public JLabel getLblDataPrevistaFim() {
        return lblDataPrevistaFim;
    }

    public JLabel getLblDataPrevistaInicio() {
        return lblDataPrevistaInicio;
    }

    public JLabel getLblDescricao() {
        return lblDescricao;
    }

    public JLabel getLblDuracaoMaximaExecucaoPorDia() {
        return lblDuracaoMaximaExecucaoPorDia;
    }

    public JLabel getLblDuracaoTotalPrevista() {
        return lblDuracaoTotalPrevista;
    }
    
    public JLabel getLblHorarios() {
        return lblHorarios;
    }

    public JLabel getLblSlotDeTempo() {
        return lblSlotDeTempo;
    }

    public JList getListTarefas() {
        return listTarefas;
    }

    public JPanel getPnlCalendarioPrincipal() {
        return pnlCalendarioPrincipal;
    }

    public JPanel getPnlExibirTarefas() {
        return pnlExibirTarefas;
    }

    public JPanel getPnlTarefas() {
        return pnlTarefas;
    }

    public JTextField getTxtDescricao() {
        return txtDescricao;
    }

    public JTextField getTxtDuracaoMaximaExecucaoPorDia() {
        return txtDuracaoMaximaExecucaoPorDia;
    }

    public JTextField getTxtDuracaoTotalPrevista() {
        return txtDuracaoTotalPrevista;
    }

    public JTextField getTxtSlotDeTempo() {
        return txtSlotDeTempo;
    }

    public JFormattedTextField getFtxfDataPrevistaFim() {
        return ftxfDataPrevistaFim;
    }

    public JFormattedTextField getFtxfDataPrevistaInicio() {
        return ftxfDataPrevistaInicio;
    }

    public JMenu getmOpcoes() {
        return mOpcoes;
    }

    public JMenuBar getMbMenu() {
        return mbMenu;
    }

    public JMenuItem getMiTarefasConcluidas() {
        return miTarefasConcluidas;
    }

    public JButton getBtnAdicionarTipo() {
        return btnAdicionarTipo;
    }

    public JComboBox getCbTiposTarefa() {
        return cbTiposTarefa;
    }

    public AdicionarTarefaController getAdicionarTarefaController() {
        return adicionarTarefaController;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public TelaPrincipalController getTelaPrincipalController() {
        return telaPrincipalController;
    }

    public JMenuItem getMiTipoEscalonamento() {
        return miTipoEscalonamento;
    }

    public DefaultListModel getListTarefasModel() {
        return listTarefasModel;
    }
    
    

}
