/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
/**
 *
 * @author Nilton
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        calendario = new javax.swing.JPanel();
        adiconarTarefa = new javax.swing.JPanel();
        lblDescriçao = new javax.swing.JLabel();
        txtDescriçao = new javax.swing.JTextField();
        lblDataPrevistaInicio = new javax.swing.JLabel();
        txtDataPrevistaInicio = new javax.swing.JTextField();
        lblDataPrevistaFim = new javax.swing.JLabel();
        txtDataPrevistaFim = new javax.swing.JTextField();
        lblDuraçaoTotalPrevista = new javax.swing.JLabel();
        txtDuraçaoTotalPrevista = new javax.swing.JTextField();
        lblDuraçaoMaximaExecuçaoPorDia = new javax.swing.JLabel();
        txtDuraçaoMaximaExecuçaoPorDia = new javax.swing.JTextField();
        btnSalvarAdiconarTarefas = new javax.swing.JButton();
        btnTipo = new javax.swing.JButton();
        lblDadosDaTarefa = new javax.swing.JLabel();
        jCBUrgente = new javax.swing.JCheckBox();
        jCBImportante = new javax.swing.JCheckBox();
        configurarCalendario = new javax.swing.JPanel();
        lblDiasUteis = new javax.swing.JLabel();
        segunda = new javax.swing.JCheckBox();
        terça = new javax.swing.JCheckBox();
        quarta = new javax.swing.JCheckBox();
        quinta = new javax.swing.JCheckBox();
        sexta = new javax.swing.JCheckBox();
        sabado = new javax.swing.JCheckBox();
        domingo = new javax.swing.JCheckBox();
        lblHorarios = new javax.swing.JLabel();
        JCB00 = new javax.swing.JCheckBox();
        JCB01 = new javax.swing.JCheckBox();
        JCB02 = new javax.swing.JCheckBox();
        JCB03 = new javax.swing.JCheckBox();
        JCB04 = new javax.swing.JCheckBox();
        JCB05 = new javax.swing.JCheckBox();
        JCB06 = new javax.swing.JCheckBox();
        JCB07 = new javax.swing.JCheckBox();
        JCB08 = new javax.swing.JCheckBox();
        JCB09 = new javax.swing.JCheckBox();
        JCB10 = new javax.swing.JCheckBox();
        JCB11 = new javax.swing.JCheckBox();
        JCB12 = new javax.swing.JCheckBox();
        JCB13 = new javax.swing.JCheckBox();
        JCB14 = new javax.swing.JCheckBox();
        JCB15 = new javax.swing.JCheckBox();
        JCB16 = new javax.swing.JCheckBox();
        JCB17 = new javax.swing.JCheckBox();
        JCB18 = new javax.swing.JCheckBox();
        JCB19 = new javax.swing.JCheckBox();
        JCB20 = new javax.swing.JCheckBox();
        JCB21 = new javax.swing.JCheckBox();
        JCB22 = new javax.swing.JCheckBox();
        JCB23 = new javax.swing.JCheckBox();
        lblSlotDeTempo = new javax.swing.JLabel();
        txtSlotDeTempo = new javax.swing.JTextField();
        lblEscalonamento = new javax.swing.JLabel();
        jRBFifo = new javax.swing.JRadioButton();
        jRBSjf = new javax.swing.JRadioButton();
        lblDataBase = new javax.swing.JLabel();
        txtDataBase = new javax.swing.JTextField();
        lblDadosCalendario = new javax.swing.JLabel();
        btnSalvarConfigurarCalendario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        calendario.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("Calendario", calendario);

        lblDescriçao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescriçao.setText("Descriçao");

        lblDataPrevistaInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDataPrevistaInicio.setText("Data prevista inicio");

        lblDataPrevistaFim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDataPrevistaFim.setText("Data prevista fim");

        lblDuraçaoTotalPrevista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDuraçaoTotalPrevista.setText("Duraçao total prevista");

        lblDuraçaoMaximaExecuçaoPorDia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDuraçaoMaximaExecuçaoPorDia.setText("Duraçao maxima execuçao por dia");

        btnSalvarAdiconarTarefas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalvarAdiconarTarefas.setText("Salvar");

        btnTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTipo.setText("Tipo");

        lblDadosDaTarefa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDadosDaTarefa.setText("Dados da tarefa");

        jCBUrgente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBUrgente.setText("Urgente");

        jCBImportante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCBImportante.setText("Importante");

        javax.swing.GroupLayout adiconarTarefaLayout = new javax.swing.GroupLayout(adiconarTarefa);
        adiconarTarefa.setLayout(adiconarTarefaLayout);
        adiconarTarefaLayout.setHorizontalGroup(
            adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adiconarTarefaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalvarAdiconarTarefas)
                .addGap(27, 27, 27))
            .addGroup(adiconarTarefaLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(lblDadosDaTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
            .addGroup(adiconarTarefaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adiconarTarefaLayout.createSequentialGroup()
                        .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataPrevistaInicio)
                            .addComponent(lblDescriçao)
                            .addComponent(lblDataPrevistaFim)
                            .addComponent(lblDuraçaoTotalPrevista)
                            .addComponent(lblDuraçaoMaximaExecuçaoPorDia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDataPrevistaInicio)
                            .addComponent(txtDescriçao)
                            .addComponent(txtDataPrevistaFim)
                            .addComponent(txtDuraçaoTotalPrevista)
                            .addComponent(txtDuraçaoMaximaExecuçaoPorDia, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                    .addGroup(adiconarTarefaLayout.createSequentialGroup()
                        .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBImportante)
                            .addComponent(jCBUrgente)
                            .addComponent(btnTipo))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        adiconarTarefaLayout.setVerticalGroup(
            adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adiconarTarefaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDadosDaTarefa)
                .addGap(46, 46, 46)
                .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescriçao)
                    .addComponent(txtDescriçao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataPrevistaInicio)
                    .addComponent(txtDataPrevistaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataPrevistaFim)
                    .addComponent(txtDataPrevistaFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDuraçaoTotalPrevista)
                    .addComponent(txtDuraçaoTotalPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adiconarTarefaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDuraçaoMaximaExecuçaoPorDia)
                    .addComponent(txtDuraçaoMaximaExecuçaoPorDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBUrgente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBImportante)
                .addGap(3, 3, 3)
                .addComponent(btnTipo)
                .addGap(81, 81, 81)
                .addComponent(btnSalvarAdiconarTarefas)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("AdicionarTarefa", adiconarTarefa);

        lblDiasUteis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDiasUteis.setText("Dias uteis");

        segunda.setText("Segunda");

        terça.setText("Terça");

        quarta.setText("Quarta");

        quinta.setText("Quinta");

        sexta.setText("Sexta");

        sabado.setText("Sabado");

        domingo.setText("Domingo");

        lblHorarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHorarios.setText("Horarios");

        JCB00.setText("00:00");

        JCB01.setText("01:00");

        JCB02.setText("02:00");

        JCB03.setText("03:00");

        JCB04.setText("04:00");

        JCB05.setText("05:00");

        JCB06.setText("06:00");

        JCB07.setText("07:00");

        JCB08.setText("08:00");

        JCB09.setText("09:00");

        JCB10.setText("10:00");

        JCB11.setText("11:00");

        JCB12.setText("12:00");

        JCB13.setText("13:00");

        JCB14.setText("14:00");

        JCB15.setText("15:00");

        JCB16.setText("16:00");

        JCB17.setText("17:00");

        JCB18.setText("18:00");

        JCB19.setText("19:00");

        JCB20.setText("20:00");

        JCB21.setText("21:00");

        JCB22.setText("22:00");

        JCB23.setText("23:00");

        lblSlotDeTempo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSlotDeTempo.setText("Slot de tempo");

        lblEscalonamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEscalonamento.setText("Escalonamento");

        buttonGroup1.add(jRBFifo);
        jRBFifo.setText("FIFO");

        buttonGroup1.add(jRBSjf);
        jRBSjf.setText("SJF");

        lblDataBase.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDataBase.setText("Data base");

        lblDadosCalendario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblDadosCalendario.setText("Dados calendario");

        btnSalvarConfigurarCalendario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalvarConfigurarCalendario.setText("Salvar");

        javax.swing.GroupLayout configurarCalendarioLayout = new javax.swing.GroupLayout(configurarCalendario);
        configurarCalendario.setLayout(configurarCalendarioLayout);
        configurarCalendarioLayout.setHorizontalGroup(
            configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configurarCalendarioLayout.createSequentialGroup()
                .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(configurarCalendarioLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(configurarCalendarioLayout.createSequentialGroup()
                                .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(segunda)
                                    .addComponent(terça)
                                    .addComponent(quarta)
                                    .addComponent(quinta)
                                    .addComponent(sexta)
                                    .addComponent(sabado)
                                    .addComponent(domingo)
                                    .addComponent(lblSlotDeTempo)
                                    .addComponent(txtSlotDeTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JCB10)
                                    .addComponent(JCB11)
                                    .addComponent(JCB09)
                                    .addComponent(JCB08)
                                    .addComponent(JCB07)
                                    .addComponent(JCB06)
                                    .addComponent(JCB00)
                                    .addComponent(JCB01)
                                    .addComponent(JCB02)
                                    .addComponent(JCB03)
                                    .addComponent(JCB04)
                                    .addComponent(JCB05))
                                .addGap(18, 18, 18)
                                .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JCB23)
                                    .addComponent(JCB19)
                                    .addComponent(JCB20)
                                    .addComponent(JCB21)
                                    .addComponent(JCB22)
                                    .addComponent(JCB15)
                                    .addComponent(JCB14)
                                    .addComponent(JCB13)
                                    .addComponent(JCB12)
                                    .addComponent(JCB16)
                                    .addComponent(JCB17)
                                    .addComponent(JCB18))
                                .addGap(58, 58, 58))
                            .addGroup(configurarCalendarioLayout.createSequentialGroup()
                                .addComponent(lblDiasUteis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHorarios)
                                .addGap(94, 94, 94)))
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBFifo)
                            .addComponent(jRBSjf)
                            .addComponent(lblEscalonamento)
                            .addGroup(configurarCalendarioLayout.createSequentialGroup()
                                .addComponent(lblDataBase)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSalvarConfigurarCalendario)
                                    .addComponent(txtDataBase, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(configurarCalendarioLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(lblDadosCalendario)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        configurarCalendarioLayout.setVerticalGroup(
            configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configurarCalendarioLayout.createSequentialGroup()
                .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(configurarCalendarioLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblDiasUteis))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configurarCalendarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblDadosCalendario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEscalonamento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblHorarios, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(configurarCalendarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(segunda)
                            .addComponent(JCB00)
                            .addComponent(JCB12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(terça)
                            .addComponent(JCB01)
                            .addComponent(JCB13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quarta)
                            .addComponent(JCB02)
                            .addComponent(JCB14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quinta)
                            .addComponent(JCB03)
                            .addComponent(JCB15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sexta)
                            .addComponent(JCB04)
                            .addComponent(JCB16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sabado)
                            .addComponent(JCB05)
                            .addComponent(JCB17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(domingo)
                            .addComponent(JCB06)
                            .addComponent(JCB18))
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(configurarCalendarioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JCB07)
                                    .addComponent(JCB19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JCB08)
                                    .addComponent(JCB20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JCB09)
                                    .addComponent(JCB21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JCB10)
                                    .addComponent(JCB22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JCB11)
                                    .addComponent(JCB23)))
                            .addGroup(configurarCalendarioLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblSlotDeTempo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSlotDeTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(configurarCalendarioLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jRBFifo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBSjf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(configurarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDataBase)
                            .addComponent(txtDataBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnSalvarConfigurarCalendario)
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Configurar calendario", configurarCalendario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox JCB00;
    private javax.swing.JCheckBox JCB01;
    private javax.swing.JCheckBox JCB02;
    private javax.swing.JCheckBox JCB03;
    private javax.swing.JCheckBox JCB04;
    private javax.swing.JCheckBox JCB05;
    private javax.swing.JCheckBox JCB06;
    private javax.swing.JCheckBox JCB07;
    private javax.swing.JCheckBox JCB08;
    private javax.swing.JCheckBox JCB09;
    private javax.swing.JCheckBox JCB10;
    private javax.swing.JCheckBox JCB11;
    private javax.swing.JCheckBox JCB12;
    private javax.swing.JCheckBox JCB13;
    private javax.swing.JCheckBox JCB14;
    private javax.swing.JCheckBox JCB15;
    private javax.swing.JCheckBox JCB16;
    private javax.swing.JCheckBox JCB17;
    private javax.swing.JCheckBox JCB18;
    private javax.swing.JCheckBox JCB19;
    private javax.swing.JCheckBox JCB20;
    private javax.swing.JCheckBox JCB21;
    private javax.swing.JCheckBox JCB22;
    private javax.swing.JCheckBox JCB23;
    private javax.swing.JPanel adiconarTarefa;
    private javax.swing.JButton btnSalvarAdiconarTarefas;
    private javax.swing.JButton btnSalvarConfigurarCalendario;
    private javax.swing.JButton btnTipo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel calendario;
    private javax.swing.JPanel configurarCalendario;
    private javax.swing.JCheckBox domingo;
    private javax.swing.JCheckBox jCBImportante;
    private javax.swing.JCheckBox jCBUrgente;
    private javax.swing.JRadioButton jRBFifo;
    private javax.swing.JRadioButton jRBSjf;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDadosCalendario;
    private javax.swing.JLabel lblDadosDaTarefa;
    private javax.swing.JLabel lblDataBase;
    private javax.swing.JLabel lblDataPrevistaFim;
    private javax.swing.JLabel lblDataPrevistaInicio;
    private javax.swing.JLabel lblDescriçao;
    private javax.swing.JLabel lblDiasUteis;
    private javax.swing.JLabel lblDuraçaoMaximaExecuçaoPorDia;
    private javax.swing.JLabel lblDuraçaoTotalPrevista;
    private javax.swing.JLabel lblEscalonamento;
    private javax.swing.JLabel lblHorarios;
    private javax.swing.JLabel lblSlotDeTempo;
    private javax.swing.JCheckBox quarta;
    private javax.swing.JCheckBox quinta;
    private javax.swing.JCheckBox sabado;
    private javax.swing.JCheckBox segunda;
    private javax.swing.JCheckBox sexta;
    private javax.swing.JCheckBox terça;
    private javax.swing.JTextField txtDataBase;
    private javax.swing.JTextField txtDataPrevistaFim;
    private javax.swing.JTextField txtDataPrevistaInicio;
    private javax.swing.JTextField txtDescriçao;
    private javax.swing.JTextField txtDuraçaoMaximaExecuçaoPorDia;
    private javax.swing.JTextField txtDuraçaoTotalPrevista;
    private javax.swing.JTextField txtSlotDeTempo;
    // End of variables declaration//GEN-END:variables
}
